version: "3.7"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    container_name: php-gallery-php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php-gallery-apache
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"
    volumes:
            - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: php-gallery-mysql
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
        - backend
    container_name: php-gallery-mailhog
  phpmyadmin:
    container_name: php-gallery-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - 8181:80
    environment:
      PMA_HOST: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
    - backend
networks:
  frontend:
  backend:
volumes:
    data: